### ISSUE TITLE
报错

### ISSUE THREAD

**Issue by lyf1134** [yjqiang/bilibili-live-tools#109]
Task exception was never retrieved
future: <Task finished coro=<BaseDanmu.ReceiveMessageLoop() done, defined at C:\Users\\Desktop\bilibili-live-tools-master\bilibili-live-tools\bilibiliCilent.py:87> exception=ValueError('not enough values to unpack (expected 2, got 1)')>
Traceback (most recent call last):
  File "C:\Users\\Desktop\bilibili-live-tools-master\bilibili-live-tools\bilibiliCilent.py", line 106, in ReceiveMessageLoop
    if not self.handle_danmu(dic):
  File "C:\Users\\Desktop\bilibili-live-tools-master\bilibili-live-tools\bilibiliCilent.py", line 164, in handle_danmu
    raffle_num, raffle_name = (msg_common.split('%>')[-1]).split('，')[0].split('个')
ValueError: not enough values to unpack (expected 2, got 1)
[2018-10-19 13:11:28] 4号弹幕姬异常或主动断开，正在处理剩余信息
[2018-10-19 13:11:28] 4号弹幕监控心跳模块主动取消
[2018-10-19 13:11:28] 4号弹幕监控分区检测模块主动取消
Task exception was never retrieved
future: <Task finished coro=<BaseDanmu.ReceiveMessageLoop() done, defined at C:\Users\\Desktop\bilibili-live-tools-master\bilibili-live-tools\bilibiliCilent.py:87> exception=ValueError('not enough values to unpack (expected 2, got 1)')>
Traceback (most recent call last):
  File "C:\Users\\Desktop\bilibili-live-tools-master\bilibili-live-tools\bilibiliCilent.py", line 106, in ReceiveMessageLoop
    if not self.handle_danmu(dic):
  File "C:\Users\\Desktop\bilibili-live-tools-master\bilibili-live-tools\bilibiliCilent.py", line 164, in handle_danmu
    raffle_num, raffle_name = (msg_common.split('%>')[-1]).split('，')[0].split('个')
ValueError: not enough values to unpack (expected 2, got 1)
[2018-10-19 13:11:28] 3号弹幕姬异常或主动断开，正在处理剩余信息
[2018-10-19 13:11:28] 3号弹幕监控心跳模块主动取消
[2018-10-19 13:11:28] 3号弹幕监控分区检测模块主动取消
Task exception was never retrieved
future: <Task finished coro=<BaseDanmu.ReceiveMessageLoop() done, defined at C:\Users\29232\Desktop\bilibili-live-tools-master\bilibili-live-tools\bilibiliCilent.py:87> exception=ValueError('not enough values to unpack (expected 2, got 1)')>
Traceback (most recent call last):
  File "C:\Users\29232\Desktop\bilibili-live-tools-master\bilibili-live-tools\bilibiliCilent.py", line 106, in ReceiveMessageLoop
    if not self.handle_danmu(dic):
  File "C:\Users\\Desktop\bilibili-live-tools-master\bilibili-live-tools\bilibiliCilent.py", line 164, in handle_danmu
    raffle_num, raffle_name = (msg_common.split('%>')[-1]).split('，')[0].split('个')
ValueError: not enough values to unpack (expected 2, got 1)
[2018-10-19 13:11:28] 2号弹幕姬异常或主动断开，正在处理剩余信息
[2018-10-19 13:11:28] 2号弹幕监控心跳模块主动取消
[2018-10-19 13:11:28] 2号弹幕监控分区检测模块主动取消
Task exception was never retrieved
future: <Task finished coro=<BaseDanmu.ReceiveMessageLoop() done, defined at C:\Users\\Desktop\bilibili-live-tools-master\bilibili-live-tools\bilibiliCilent.py:87> exception=ValueError('not enough values to unpack (expected 2, got 1)')>
Traceback (most recent call last):
  File "C:\Users\\Desktop\bilibili-live-tools-master\bilibili-live-tools\bilibiliCilent.py", line 106, in ReceiveMessageLoop
    if not self.handle_danmu(dic):
  File "C:\Users\\Desktop\bilibili-live-tools-master\bilibili-live-tools\bilibiliCilent.py", line 164, in handle_danmu
    raffle_num, raffle_name = (msg_common.split('%>')[-1]).split('，')[0].split('个')
ValueError: not enough values to unpack (expected 2, got 1)
[2018-10-19 13:11:28] 1号弹幕姬异常或主动断开，正在处理剩余信息
[2018-10-19 13:11:28] 1号弹幕监控心跳模块主动取消
[2018-10-19 13:11:28] 1号弹幕监控分区检测模块主动取消
[2018-10-19 13:11:28] 4号弹幕收尾模块状态True
[2018-10-19 13:11:28] 4号弹幕姬退出，剩余任务处理完毕
[2018-10-19 13:11:28] 3号弹幕收尾模块状态True
[2018-10-19 13:11:28] 3号弹幕姬退出，剩余任务处理完毕
[2018-10-19 13:11:28] 2号弹幕收尾模块状态True
[2018-10-19 13:11:28] 2号弹幕姬退出，剩余任务处理完毕
[2018-10-19 13:11:28] 1号弹幕收尾模块状态True
[2018-10-19 13:11:28] 1号弹幕姬退出，剩余任务处理完毕
[2018-10-19 13:11:28] 1号弹幕监控选择房间（23058）
[2018-10-19 13:11:28] # 正在启动抽奖监控弹幕姬
[2018-10-19 13:11:28] 2号弹幕监控选择房间（5085）
[2018-10-19 13:11:28] # 正在启动抽奖监控弹幕姬
[2018-10-19 13:11:28] 1号弹幕监控已连接b站服务器
[2018-10-19 13:11:28] 1号弹幕监控进入房间（23058）
[2018-10-19 13:11:28] 4号弹幕监控选择房间（8603205）
[2018-10-19 13:11:28] # 正在启动抽奖监控弹幕姬
[2018-10-19 13:11:28] 3号弹幕监控选择房间（40903）
[2018-10-19 13:11:28] # 正在启动抽奖监控弹幕姬
[2018-10-19 13:11:28] 2号弹幕监控已连接b站服务器
[2018-10-19 13:11:28] 2号弹幕监控进入房间（5085）
[2018-10-19 13:11:28] 4号弹幕监控已连接b站服务器
[2018-10-19 13:11:28] 3号弹幕监控已连接b站服务器
[2018-10-19 13:11:28] 4号弹幕监控进入房间（8603205）
[2018-10-19 13:11:28] 3号弹幕监控进入房间（40903）

**Comment by yjqiang** [comment]
这是bug  我查看一下

**Comment by yjqiang** [comment]
b站个sb  又出来了个欧气能量  格式与之前不一样  神经病
