### ISSUE TITLE
Linux系统，模块均已安装，Python是3.6，无法运行run.py

### ISSUE THREAD

**Issue by SGlace** [yjqiang/bilibili-live-tools#50]
大佬，你好，我用的pi，Linux系统，模块均已安装，Python是3.6，无法运行run.py，运行以后代码如下，请你帮忙看一下，谢谢！

``Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 589, in urlopen
    conn = self._get_conn(timeout=pool_timeout)
  File "/usr/local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 251, in _get_conn
    return conn or self._new_conn()
  File "/usr/local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 827, in _new_conn
    raise SSLError("Can't connect to HTTPS URL because the SSL "
urllib3.exceptions.SSLError: Can't connect to HTTPS URL because the SSL module is not available.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/requests/adapters.py", line 440, in send
    timeout=timeout
  File "/usr/local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 639, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/usr/local/lib/python3.6/site-packages/urllib3/util/retry.py", line 388, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='passport.bilibili.com', port=443): Max retries exceeded with url: /api/oauth2/getKey (Caused by SSLError("Can't connect to HTTPS URL because the SSL module is not available.",))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "run.py", line 9, in <module>
    login = Login().success()
  File "/root/bilibili-live-tools-1.5/login.py", line 26, in success
    value = self.GetHash()
  File "/root/bilibili-live-tools-1.5/login.py", line 19, in GetHash
    response = requests.post(url, data=params)
  File "/usr/local/lib/python3.6/site-packages/requests/api.py", line 112, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/requests/api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/requests/sessions.py", line 508, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.6/site-packages/requests/sessions.py", line 618, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/requests/adapters.py", line 506, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: HTTPSConnectionPool(host='passport.bilibili.com', port=443): Max retries exceeded with url: /api/oauth2/getKey (Caused by SSLError("Can't connect to HTTPS URL because the SSL module is not available.",))

**Comment by SGlace** [comment]
![default](https://user-images.githubusercontent.com/22759345/40101835-40fc7742-591b-11e8-9425-4ed0eff199bb.png)

**Comment by lovelyyoshino** [comment]
根据错误来看是你的SSL出现问题，重定义到HTTPS中了，从而未连接

**Comment by lovelyyoshino** [comment]
应该是没问题的，你这个不清楚了，实在不行自己获取到accesskey和cookies吧

**Comment by colorsakura** [comment]
这个是编译安装Python的时候，ssl等模块没安装

**Comment by SGlace** [comment]
感谢各位大佬，已解决。

`sudo apt-get install mysql-server python-mysqldb`

即可解决

**Comment by yjqiang** [comment]
@SGlace  应该是无心之举，mysql与本项目无关

**Comment by SGlace** [comment]
@yjqiang 找了很多方法，用了这个就莫名其妙的好了。也有可能是之前补装的ssl起了作用，给人一个借鉴吧，还得谢谢大佬！

**Comment by SGlace** [comment]
@yjqiang 还有个问题想请教一下，大佬！这个username和password不是保存在本地的吗？怎样做到自动登录？

**Comment by yjqiang** [comment]
保持登陆使用cookie等进行状态保持 conf配置文件bilibili中有

**Comment by SGlace** [comment]
@yjqiang  大佬，我发现你似乎没有在release里发布？

**Comment by yjqiang** [comment]
release我觉得麻烦。。。欢迎你来提交合并
